### ISSUE TITLE
Element-Plus 语言

### ISSUE THREAD

**Issue by dhjz** [WeBankFinTech/KoalaForm#11]
内置的Element-Plus 语言怎么设置中文呀

**Comment by aringlai** [comment]
可参考官网文档https://element-plus.org/zh-CN/guide/i18n.html，使用插件安装的形式或者ConfigProvider

**Comment by dhjz** [comment]
这个框架是引用的内置的element-plus , 我在项目的代码里面加了ElementPlus语言配置貌似不起作用, 另外useForm有个bug, 就是设置默认值的时候, 数字0设置不起, 应该是这句需要优化下吧?
initModel[field.name] = field.defaultValue || (field.type === 'array' ? [] : null)

**Comment by aringlai** [comment]
1、试了下，语言设置两种方式都是OK的，可以提供一下你设置的代码看看。
2、初始化0确实是bug，可以先调用api `initFields`先处理

**Comment by ae86yyk** [comment]
@dhjz 你的element-plus版本是多少，我之前试的时候ConfigProvider里的namespace也不生效，2.3.7之后的版本就可以。

**Comment by dhjz** [comment]
"element-plus": "2.2.27"
main,js里面设置了
app.use(ElementPlus, {
  locale: locale,
  // 支持 large、default、small
  size: Cookies.get('size') || 'default'
})

**Comment by aringlai** [comment]
因为element-plugin里写了element-plus的依赖版本，所以导致你本地存在两个版本的element-plus。升级到`@koala-form/element-plugin@2.0.3`，已经将依赖版本去掉，跟随主项目，避免多个版本。

可参考例子
https://stackblitz.com/edit/vitejs-vite-fm5hl4?file=src%2Fmain.js
