### ISSUE TITLE
element-plugin pager layout

### ISSUE THREAD

**Issue by dhjz** [WeBankFinTech/KoalaForm#12]
element-plugin的 pager的 layout设置了没有作用会被覆盖呀, 可以开放出这个设置吗

**Comment by aringlai** [comment]
```js
useCurd({
 // ...
 pager: {
     pager: { props: {
       // 这里设置分页组件属性
    } }
 }
})
```

**Comment by dhjz** [comment]
设置了不起作用哦, 貌似是被覆盖了

**Comment by aringlai** [comment]
提供一下代码

**Comment by dhjz** [comment]
element-plugin index.js 这里有个合并选项, 另外如果自定义了应该还要在curd里面监听onSizeChange哈

api.on('pagerSchemeLoaded', ({ ctx }) => {
        const pagerScheme = ctx.schemes[0];
        mergeRefProps(pagerScheme, 'props', {
            layout: 'prev, pager, next',
            total: computed(() => { var _a, _b; return (_b = (_a = ctx.modelRef) === null || _a === void 0 ? void 0 : _a.value) === null || _b === void 0 ? void 0 : _b.totalCount; }),
            background: true,
        });
    });

**Comment by dhjz** [comment]
element-plugin index.js 这里有个合并选项, 另外如果自定义了应该还要在curd里面监听onSizeChange哈

api.on('pagerSchemeLoaded', ({ ctx }) => {
        const pagerScheme = ctx.schemes[0];
        mergeRefProps(pagerScheme, 'props', {
            layout: 'prev, pager, next',
            total: computed(() => { var _a, _b; return (_b = (_a = ctx.modelRef) === null || _a === void 0 ? void 0 : _a.value) === null || _b === void 0 ? void 0 : _b.totalCount; }),
            background: true,
        });
    });

**Comment by aringlai** [comment]
onSizeChange应该是在events里面
