### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by ae86yyk** [WeBankFinTech/KoalaForm#3]
使用element-plugin
useCurd  点击新增按钮时报错
![image](https://github.com/WeBankFinTech/KoalaForm/assets/4171863/8a442715-9c55-4c9e-9ce3-7d4ee303419d)

请问哪里配置的不对
参考demo https://stackblitz.com/edit/vitejs-vite-abxniv

**Comment by aringlai** [comment]
移除jsx方式，插件请升级到2.0.1
