### ISSUE TITLE
表单布局能做到什么程度

### ISSUE THREAD

**Issue by latte03** [WeBankFinTech/KoalaForm#7]
除了一般的label 和 控件的位置关系，别的布局支持么，比如row/col之类的

**Comment by aringlai** [comment]
当前useForm场景的布局可通过Form组件的layout属性调整，如果需要通过row/col控制FormItem可扩展插件修改scheme实现。插件扩展请参考：https://koala-form.mumblefe.cn/zh/guide/plugin/how.html
